name: boom
favicon: null
layout_spectrum: 0.782166917109862
typography_spectrum: 0.7179020198527724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3226993568241596
  lightness: 0.7670115793589503
  saturation: 0.4497412578202784
  rhythmicContrast: 0.26809141342528164
purpose: []
